# **Numpy**


### **Creating array using NumPy**

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int64')

In [5]:
type(arr)

numpy.ndarray

NumPy Arrays using lists

In [5]:
lst =[1,2,3,4,5]
type(lst)

list

In [6]:
arr1 = np.array(list)
type(arr1)

numpy.ndarray

NumPy Arrays?

1.   Matrices
2.   Vectors



In [7]:
# matrix
# 1D , 2D , 3D
arr2 = np.array([[[1,2,3,4,5],
                    [7,8,9,10,11],
                    [7,8,9,10,11]],

                    [[1,2,3,4,5],
                    [7,8,9,10,11],
                    [7,8,9,10,11]]])
arr2


array([[[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11]],

       [[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11]]])

In [8]:
# row vector
row_vector = np.array([[81,82,83,84],[1,2,5,6]])

row_vector

array([[81, 82, 83, 84],
       [ 1,  2,  5,  6]])

In [9]:
# column vector
column_vector = np.array([[81],
                          [82],
                          [83]])

column_vector

array([[81],
       [82],
       [83]])

NumPy Arrays using built-in methods






In [11]:
# arange
# zeros
# ones

# linspace - HW

array = np.arange(15)
print(array)
array = np.arange(5,20)#(start, stop) (include, exclude)
print(array)
array = np.arange(10,2,-1)
array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([10,  9,  8,  7,  6,  5,  4,  3])

In [12]:
zero = np.zeros(5)
print(zero)

one = np.ones(5)
print(one)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [14]:
arr =np.array([[1,2,3],[7,8,9]])
arr.shape

(2, 3)

arr.reshape

In [13]:
#reshapre
arr1 = np.arange(10,35)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [17]:
arr1.shape

(25,)

In [14]:
arr1.reshape(5,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

Array with random numbers

In [15]:
# HW np.random.rand
r=np.random.rand(6)
r

array([0.72604732, 0.78290069, 0.96936898, 0.34954982, 0.46070002,
       0.29371074])

Array with random integers

In [16]:
# HW np.random.randint
r1=np.random.randint(10)
r1

7

Maximum and Minimum

In [18]:
print(arr1.max())
print(arr1.min())

34
10


Indexing

In [34]:
arr2 = np.array([[1,2,3,4,5],
                [7,8,9,10,11],
                [78,812,92,110,1]])

arr2[:,1:]

array([[  2,   3,   4,   5],
       [  8,   9,  10,  11],
       [812,  92, 110,   1]])

Slicing


In [19]:
arr2[1:]

array([[[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11]]])

In [21]:
arr2[1:,1]

array([[ 7,  8,  9, 10, 11]])

In [22]:
arr2[1:,1:3]

array([[[ 7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11]]])

Join two arrays



#### Concatenate function

In [23]:
arr1 = np.array([[1, 2, 3],[3,4,7]])

arr2 = np.array([[4, 5, 6],[5,8,1]])

arr = np.concatenate((arr2,arr1))

arr

array([[4, 5, 6],
       [5, 8, 1],
       [1, 2, 3],
       [3, 4, 7]])

#### Stack function

In [32]:
arr1 = np.array([1,2,3])
arr2 = [4,5,6]
arr3 = [7,8,9]

In [25]:
arr1.ndim

1

In [29]:
arr3 = np.stack((arr1,arr2), axis=1)
arr3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
arr4 = np.stack((arr1,arr2,arr3), axis=1)
arr4

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Split Into Arrays

In [35]:
array_big = np.array([1,2,3,4,12,5,6,7,8,9,10,1,5,0,25,324,78,8])
len(array_big)

18

In [36]:
new_arr =np.array_split(array_big,5)

In [37]:
new_arr[2]

array([ 8,  9, 10,  1])

In [38]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr2 = np.array_split(arr2d, 2, axis = 0)

new_arr2

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

Search()

In [39]:
array_big_10 = np.where(array_big >= 10)
array_big_10

(array([ 4, 10, 14, 15, 16]),)

In [40]:
array_big_1 = np.where(array_big == 10)
array_big_1

(array([10]),)

Sort()

In [41]:
array_big_sort = np.sort(array_big)[::-1]
array_big_sort

array([324,  78,  25,  12,  10,   9,   8,   8,   7,   6,   5,   5,   4,
         3,   2,   1,   1,   0])