In [1]:
import numpy as np

In [2]:
import sys

In [11]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [31]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [12]:
a.dtype

dtype('int16')

In [13]:
a.itemsize

2

In [14]:
a.size

3

In [15]:
a.size*a.itemsize

6

In [16]:
a.nbytes

6

In [17]:
b.itemsize

8

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
a.shape

(2, 7)

In [22]:
print(a[1,-4])

11


In [23]:
print(a[0,:])

[1 2 3 4 5 6 7]


In [24]:
print(a[:,4])

[ 5 12]


In [25]:
print(a[0,1:6:2])

[2 4 6]


In [26]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
print(b[0,1,1])

4


In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [33]:
np.full(b.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [34]:
np.full_like(b,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [35]:
np.random.rand(4,4)

array([[0.34524183, 0.36813621, 0.39729507, 0.89771011],
       [0.19889942, 0.2371749 , 0.43224194, 0.5341797 ],
       [0.26080639, 0.4322322 , 0.95074181, 0.85992692],
       [0.91979294, 0.97118477, 0.22710269, 0.12199437]])

In [36]:
np.random.random_sample(b.shape)

array([[0.9432117 , 0.85938214, 0.47307806],
       [0.82659654, 0.83914884, 0.49019792]])

In [39]:
np.random.randint(3,7,size=(3,3))

array([[3, 5, 3],
       [5, 3, 6],
       [4, 6, 5]], dtype=int32)

In [40]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [52]:
x=np.ones((5,5))
y=np.zeros((3,3))
y[1,1]=9
x[1:4,1:4]=y[:,:]
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
p=np.array([1,2,3])
q=p.copy()
q[0]=5
print(p)

[1 2 3]


In [56]:
p+2

array([3, 4, 5])

In [57]:
p-2

array([-1,  0,  1])

In [58]:
p*2

array([2, 4, 6])

In [59]:
p/2

array([0.5, 1. , 1.5])

In [60]:
p**2

array([1, 4, 9])

In [61]:
np.sin(p)

array([0.84147098, 0.90929743, 0.14112001])

In [62]:
np.cos(p)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [64]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [66]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [67]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.min(stats)

np.int64(1)

In [70]:
np.max(stats)

np.int64(6)

In [72]:
np.min(stats,axis=1)

array([1, 4])

In [73]:
np.sum(stats)

np.int64(21)

In [74]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [75]:
np.sum(stats,axis=1)

array([ 6, 15])

In [76]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [77]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [81]:
file=np.genfromtxt('data.txt',delimiter=',')
file=file.astype('int32')
print(file)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [82]:
file>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True])

In [83]:
file[file>10]

array([11, 12, 13, 14, 15, 16, 17, 18], dtype=int32)